name: us_scipy21
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.3.2
  - cartopy=0.19.0.post1
  - colorcet=2.0.6
  - contextily=1.1.0
  - dask=2021.5.0
  - dask-core=2021.5.0
  - dask-glm=0.2.0
  - dask-ml=1.9.0
  - datashader=0.12.1
  - datashape=0.5.4
  - descartes=1.1.0
  - distributed=2021.5.0
  - fiona=1.8.18
  - geographiclib=1.52
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geopy=2.1.0
  - geos=3.9.1
  - geotiff=1.6.0
  - glib=2.68.2
  - glib-tools=2.68.2
  - gmpy2=2.1.0b5
  - graphite2=1.3.14
  - graphviz=2.47.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - holoviews=1.14.4
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.2
  - jinja2=3.0.0
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - networkx=2.5
  - nodejs=15.3.0
  - notebook=6.4.0
  - numba=0.53.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - pandas=1.2.4
  - panel=0.11.3
  - pango=1.48.5
  - param=1.10.1
  - parquet-cpp=1.5.1
  - pip=21.1.1
  - postgresql=13.3
  - proj=7.2.0
  - pyarrow=4.0.0
  - pycparser=2.20
  - pygeos=0.10
  - pyproj=3.1.0
  - pysal=2.4.0
  - pyshp=2.1.3
  - rasterio=1.2.6
  - rasterstats=0.15.0
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - setuptools=52.0.0
  - shapely=1.7.1
  - snappy=1.1.8
  - statsmodels=0.12.2
  - pip:
    - arrow==1.1.0
    - cookiecutter==1.7.3
    - currencyconverter==0.16.1
    - dask-labextension==5.0.2
    - geoviews==1.9.1
    - hvplot==0.7.2
    - jinja2-time==0.2.0
    - jupyter-bokeh==3.0.2
    - jupyter-server-proxy==3.0.2
    - wget==3.2
